name: Trigger Secondo avvio CreateDatasetRecommeder

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Secondo avvio CreateDatasetRecommeder"]
    types:
      - completed

jobs:
  generate_failure:
    runs-on: ubuntu-latest
    
    if: ${{ github.event.workflow_run.conclusion == 'failure'}}

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests

      - name: Sleep for 10 minutes
        run: sleep 600

      - name: Run Python script (which generates a failure)
        run: python -c "import sys; sys.exit(1)"
